"""
Django settings for Agrotech project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from decouple import config, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-dummy-key-for-build')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='', cast=Csv())

# Enable Authentication Backend
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

# Application definition

# Application definition

INSTALLED_APPS = [
    'home.apps.HomeConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'cloudinary_storage',
    'django.contrib.staticfiles',
    'cloudinary',
]

# Cloudinary — media storage for profile pictures & uploaded assets
CLOUDINARY_CLOUD_NAME = config('CLOUDINARY_CLOUD_NAME', default='')
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': CLOUDINARY_CLOUD_NAME,
    'API_KEY': config('CLOUDINARY_API_KEY', default=''),
    'API_SECRET': config('CLOUDINARY_API_SECRET', default=''),
}
import cloudinary
cloudinary.config(
    cloud_name=CLOUDINARY_CLOUD_NAME,
    api_key=config('CLOUDINARY_API_KEY', default=''),
    api_secret=config('CLOUDINARY_API_SECRET', default=''),
    secure=True
)

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Agrotech.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'home.context_processors.agrotech_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'Agrotech.wsgi.application'


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': config('DB_NAME', default='defaultdb'),
        'USER': config('DB_USERNAME', default='avnadmin'),
        'PASSWORD': config('DB_PASSWORD', default=''),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='3306'),
        'OPTIONS': {
            'charset': 'utf8mb4',
            'connect_timeout': 10,
            'ssl': {'ca': None},  # Aiven requires SSL, ca=None accepts server cert
        },
        'TEST': {
            'NAME': 'test_agrotech_db',
        },
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

# FIX: Changed from UTC to India Standard Time
TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

# FIX: Removed duplicate STATIC_URL definition
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"
STORAGES = {
    "default": {
        "BACKEND": (
            "cloudinary_storage.storage.MediaCloudinaryStorage"
            if CLOUDINARY_CLOUD_NAME else
            "django.core.files.storage.FileSystemStorage"
        ),
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}
STATICFILES_STORAGE = STORAGES["staticfiles"]["BACKEND"]
WHITENOISE_MANIFEST_STRICT = False

# Authentication URLs
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'         # FIX: Added missing LOGIN_REDIRECT_URL
LOGOUT_REDIRECT_URL = '/login/'  # FIX: Added missing LOGOUT_REDIRECT_URL

# Media files setup for user profile picture uploads
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Security settings for production deployment (active when DEBUG=False)
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_REFERRER_POLICY = 'same-origin'
    SECURE_HSTS_SECONDS = 3600
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    X_FRAME_OPTIONS = 'DENY'

# Rate Limiting view handler
RATELIMIT_VIEW = 'home.views.ratelimited_error'

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {'format': '{levelname} {asctime} {module} {message}', 'style': '{'},
    },
    'handlers': {
        'console': {'class': 'logging.StreamHandler', 'formatter': 'verbose'},
    },
    'root': {'handlers': ['console'], 'level': 'INFO'},
    'loggers': {
        'django': {'handlers': ['console'], 'level': 'INFO', 'propagate': False},
        'home': {'handlers': ['console'], 'level': 'DEBUG', 'propagate': False},
    },
}

# Email configurations
EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = config('EMAIL_HOST', default='')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default=EMAIL_HOST_USER)
ADMIN_NOTIFICATION_EMAIL = config('ADMIN_NOTIFICATION_EMAIL', default='')

AGROTECH_HELPLINE = config('AGROTECH_HELPLINE', default='+91 9318302850')

# Cloudinary CDN URLs for all project images (uploaded via scripts/upload_static_to_cloudinary.py)
# These replace local static file references in templates with fast Cloudinary CDN delivery
CLOUDINARY_IMAGE_URLS = {
    "24": "https://res.cloudinary.com/ddwrdkpkv/image/upload/v1787384798/agrotech/24.jpg",
    "ads": "https://res.cloudinary.com/ddwrdkpkv/image/upload/v1787384799/agrotech/ADS.jpg",
    "afs": "https://res.cloudinary.com/ddwrdkpkv/image/upload/v1787384800/agrotech/AFS.jpg",
    "ceo": "https://res.cloudinary.com/ddwrdkpkv/image/upload/v1787384802/agrotech/CEO.jpg",
    "cha": "https://res.cloudinary.com/ddwrdkpkv/image/upload/v1787384803/agrotech/CHA.jpg",
    "chm": "https://res.cloudinary.com/ddwrdkpkv/image/upload/v1787384804/agrotech/CHM.jpg",
    "cmo": "https://res.cloudinary.com/ddwrdkpkv/image/upload/v1787384805/agrotech/CMO.jpg",
    "cto": "https://res.cloudinary.com/ddwrdkpkv/image/upload/v1787384806/agrotech/CTO.jpg",
    "cw": "https://res.cloudinary.com/ddwrdkpkv/image/upload/v1787384807/agrotech/cw.jpg",
    "ds": "https://res.cloudinary.com/ddwrdkpkv/image/upload/v1787384808/agrotech/ds.jpg",
    "ee": "https://res.cloudinary.com/ddwrdkpkv/image/upload/v1787384809/agrotech/ee.jpg",
    "fms": "https://res.cloudinary.com/ddwrdkpkv/image/upload/v1787384810/agrotech/FMS.jpg",
    "ga": "https://res.cloudinary.com/ddwrdkpkv/image/upload/v1787384811/agrotech/GA.jpg",
    "hs": "https://res.cloudinary.com/ddwrdkpkv/image/upload/v1787384812/agrotech/HS.jpg",
    "hwd1": "https://res.cloudinary.com/ddwrdkpkv/image/upload/v1787384812/agrotech/HWD1.jpg",
    "ic": "https://res.cloudinary.com/ddwrdkpkv/image/upload/v1787384813/agrotech/ic.jpg",
    "is": "https://res.cloudinary.com/ddwrdkpkv/image/upload/v1787384815/agrotech/is.jpg",
    "lm": "https://res.cloudinary.com/ddwrdkpkv/image/upload/v1787384817/agrotech/LM.jpg",
    "logo": "https://res.cloudinary.com/ddwrdkpkv/image/upload/v1787384818/agrotech/logo.jpg",
    "ml": "https://res.cloudinary.com/ddwrdkpkv/image/upload/v1787384820/agrotech/ML.jpg",
    "om": "https://res.cloudinary.com/ddwrdkpkv/image/upload/v1787384822/agrotech/OM.jpg",
    "ov": "https://res.cloudinary.com/ddwrdkpkv/image/upload/v1787384823/agrotech/ov.jpg",
    "pcs": "https://res.cloudinary.com/ddwrdkpkv/image/upload/v1787384826/agrotech/PCS.jpg",
    "pp": "https://res.cloudinary.com/ddwrdkpkv/image/upload/v1787384829/agrotech/PP.jpg",
    "scm": "https://res.cloudinary.com/ddwrdkpkv/image/upload/v1787384830/agrotech/SCM.jpg",
    "slide1": "https://res.cloudinary.com/ddwrdkpkv/image/upload/v1787384831/agrotech/slide1.jpg",
    "slide2": "https://res.cloudinary.com/ddwrdkpkv/image/upload/v1787384832/agrotech/slide2.jpg",
    "slide3": "https://res.cloudinary.com/ddwrdkpkv/image/upload/v1787384833/agrotech/slide3.jpg",
    "sm": "https://res.cloudinary.com/ddwrdkpkv/image/upload/v1787384834/agrotech/sm.jpg",
    "tip1": "https://res.cloudinary.com/ddwrdkpkv/image/upload/v1787384835/agrotech/Tip1.jpg",
    "tip2": "https://res.cloudinary.com/ddwrdkpkv/image/upload/v1787384836/agrotech/Tip2.jpg",
    "tip3": "https://res.cloudinary.com/ddwrdkpkv/image/upload/v1787384837/agrotech/Tip3.jpg",
    "tw": "https://res.cloudinary.com/ddwrdkpkv/image/upload/v1787384838/agrotech/TW.jpg",
    "wc": "https://res.cloudinary.com/ddwrdkpkv/image/upload/v1787384839/agrotech/wc.jpg",
    # Legends
    "george_carver": "https://res.cloudinary.com/ddwrdkpkv/image/upload/v1787384840/agrotech/legends/george_carver.jpg",
    "gregor_mendel": "https://res.cloudinary.com/ddwrdkpkv/image/upload/v1787384841/agrotech/legends/gregor_mendel.jpg",
    "gurdev_khush": "https://res.cloudinary.com/ddwrdkpkv/image/upload/v1787384842/agrotech/legends/gurdev_khush.jpg",
    "justus_liebig": "https://res.cloudinary.com/ddwrdkpkv/image/upload/v1787384843/agrotech/legends/justus_liebig.jpg",
    "ms_swaminathan": "https://res.cloudinary.com/ddwrdkpkv/image/upload/v1787384845/agrotech/legends/ms_swaminathan.jpg",
    "norman_borlaug": "https://res.cloudinary.com/ddwrdkpkv/image/upload/v1787384846/agrotech/legends/norman_borlaug.jpg",
    "subhash_palekar": "https://res.cloudinary.com/ddwrdkpkv/image/upload/v1787384847/agrotech/legends/subhash_palekar.jpg",
    "verghese_kurien": "https://res.cloudinary.com/ddwrdkpkv/image/upload/v1787384848/agrotech/legends/verghese_kurien.jpg",
}
