# Generated by Django 6.0.7 on 2026-08-02 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_contact_options_contact_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, default='+91 9876543210', max_length=15, null=True)),
                ('state', models.CharField(blank=True, default='Gujarat', max_length=100, null=True)),
                ('district', models.CharField(blank=True, default='Patan', max_length=100, null=True)),
                ('farm_size', models.CharField(blank=True, default='12.5 Acres', max_length=50, null=True)),
                ('primary_crops', models.CharField(blank=True, default='Wheat, Cotton, Groundnut', max_length=200, null=True)),
                ('experience_years', models.IntegerField(default=5)),
                ('bio', models.TextField(blank=True, default='Passionate about modern sustainable farming and tech adoption in agriculture.', null=True)),
                ('avatar', models.CharField(choices=[('farmer1', '👨\u200d🌾 Traditional Farmer'), ('farmer2', '👩\u200d🌾 Tech Farmer'), ('expert', '👨\u200d🔬 Agri Expert'), ('manager', '🚜 Farm Manager')], default='farmer1', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
