# Generated by Django 5.1.5 on 2026-08-22 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_newslettersubscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.URLField(blank=True, help_text='Cloudinary CDN URL for profile photo', max_length=500, null=True),
        ),
    ]
